name: Update readme with blog posts
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://elboudali.com/rss.xml"
          max_post_count: 5
          template: "* [$title]($url) — $category"
          date_format: "MMM DD, YYYY"
