name: Update readme with blog posts
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
permissions:
  contents: write
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://elboudali.com/rss.xml"
          max_post_count: 5
          custom_tags: "readingTime/category/"
          template: '* [$title]($url) - $readingTime$newline'
